from fastapi import HTTPException

from sqlalchemy.orm import Session

from models.companies import Company
from models.email import Email

from core.email_sender import send_email

def generate(
    db: Session,
    current_user,
    payload
):

    company = db.query(Company).filter(
        Company.id == payload.company_id
    ).first()

    if not company:
        raise HTTPException(
            status_code=404,
            detail="Company not found"
        )

    generated = {"subject": "subject generated by ai", "body":"body generated by ai"}

    email = Email(
        id = current_user.email,
        user_id=current_user.user_id,
        company_id=company.id,
        subject=generated["subject"],
        body=generated["body"],
        status="draft"
    )

    db.add(email)

    db.commit()

    db.refresh(email)

    return email


def approve(
    db: Session,
    current_user,
    email_id: str
):

    email = db.query(Email).filter(
        Email.id == email_id,
        Email.user_id == current_user.user_id
    ).first()

    if not email:
        raise HTTPException(
            status_code=404,
            detail="Email not found"
        )

    email.status = "approved"

    db.commit()

    db.refresh(email)

    return email

def send(
    db: Session,
    current_user,
    email_id: str
):

    email = db.query(Email).filter(
        Email.id == email_id,
        Email.user_id == current_user.user_id
    ).first()

    if not email:
        raise HTTPException(
            status_code=404,
            detail="Email not found"
        )

    if email.status != "approved":
        raise HTTPException(
            status_code=400,
            detail="Email must be approved before sending"
        )

    company = db.query(Company).filter(
        Company.id == email.company_id
    ).first()

    if not company:
        raise HTTPException(
            status_code=404,
            detail="Company not found"
        )

    send_email(
        to_email=str(company.company_email),
        subject=email.subject,
        body=email.body
    )

    email.status = "sent"

    db.commit()

    db.refresh(email)

    return email

def get_email_service(
    db: Session,
    current_user,
    email_id: str
):

    email = db.query(Email).filter(
        Email.id == email_id,
        Email.user_id == current_user.user_id
    ).first()

    if not email:
        raise HTTPException(
            status_code=404,
            detail="Email not found"
        )

    return email

def get_all_emails_service(
    db: Session,
    current_user
):

    emails = db.query(Email).filter(
        Email.user_id == current_user.user_id
    ).all()

    return emails

def delete_email_service(
    db: Session,
    current_user,
    email_id: str
):

    email = db.query(Email).filter(
        Email.id == email_id,
        Email.user_id == current_user.id
    ).first()

    if not email:
        raise HTTPException(
            status_code=404,
            detail="Email not found"
        )

    db.delete(email)

    db.commit()

    return